### ISSUE TITLE
List command

### ISSUE THREAD

**Issue by alanplotko** [Wizzcotch/350p2#12]
`list`

List all the names and sizes of the files in the file system.

Personal Note: Take advantage of filemap to get all filenames and then locate their inodes using the CR/imap/segment file reading to get the file sizes.

**Comment by alanplotko** [comment]
Completed. Needs further testing.

**Comment by alanplotko** [comment]
@Wizzcotch, issue at segment 3.

**Comment by lumapat** [comment]
Resolved after fixing minor issue in IMap.cpp concerning `segmentNum`.
