### ISSUE TITLE
Cat command

### ISSUE THREAD

**Issue by alanplotko** [Wizzcotch/350p2#9]
`cat <lfs_filename>`

Display the contents of <lfs_filename> from within your file and print them on the screen.  (All files that we use will be text files.)

**Comment by alanplotko** [comment]
@Wizzcotch, potential future issue: needing to detect and fetch data blocks that overflow into the next segment.

**Comment by alanplotko** [comment]
Cat and display work, except for the above issue. See #18.

**Comment by alanplotko** [comment]
@Wizzcotch Add support for files in memory and not in disk.

**Comment by lumapat** [comment]
Resolved. See #18.
